# Uses Latest Appleseed.Portal Build 
# This file compiles the github.com/portal Repositiory

FROM microsoft/iis

SHELL ["powershell"]

MAINTAINER ANANT Corporation www.anant.us | Report Issues : https://github.com/Appleseed/portal-stack/issues