# Windows Portal Stack Load Balance Set using https://traefik.io/
version: '2.1'
services:
  db-mssql-2016:
    build:
     context: ..\
     dockerfile: \db\mssql\Dockerfile.server
    environment:
      sa_password: "Password1"
      ACCEPT_EULA: Y

    #Use 1433:1433 as long as port 1433 is blocked externally on the HOST
    ports:
      - "1433:1433"

  web-appleseed-portal1:
    build:
      context: ..\
      dockerfile: portal\windows\Dockerfile
    
    depends_on:
      - "db-mssql-2016"

    links:
      - "db-mssql-2016"
    #Port 80 is exposed on the container but will be given a radom blocked host port ( so only the host can use at first)  
    
      
  web-appleseed-portal2:
    build:
      context: ..\
      dockerfile: portal\windows\Dockerfile
    
    depends_on:
      - "db-mssql-2016"

    links:
      - "db-mssql-2016"

    
      
  web-load-balance-proxy:
    build:
       context: ..\
        dockerfile: traefik\windows\Dockerfile
    links:
     - web-appleseed-portal1
     - web-appleseed-portal2


networks:
    default:
       external:
           name: nat
