version: '2.1'
services:
  db-mssql-express-2016:
    build:
     context: ..\
     dockerfile: \db\mssql\Dockerfile
    environment:
      sa_password: "Password1"
      ACCEPT_EULA: Y
    #Port 1433 is usually blocked externally on windows host.  If it is not, use a dynamic / blocked internal port
    ports:
      - "1433:1433"

  web-appleseed-portal:
    build:
      context: ..\
      dockerfile: portal\windows\Dockerfile
    
    depends_on:
      - "db-mssql-express-2016"

    links:
      - "db-mssql-express-2016"
    #Port 80 is exposed on the container and host.  Admins can modify this in their own version. 
    ports:
      - "80:80"

networks:
    default:
       external:
           name: nat
