version: '2.1'
services:
  db-mssql-express-2016:
    build:
     context: ..\
     dockerfile: \sql\
    environment:
      sa_password: "Password1"
      ACCEPT_EULA: Y

    ports:
      - "1433:1433"

  web-appleseed-portal:
    build:
      context: ..\
      dockerfile: portal\windows\servercore\
    
    depends_on:
      - "db-mssql-express-2016"

    links:
      - "db-mssql-express-2016"

    ports:
      - "80:80"

networks:
  default:
    external:
      name: nat
