version: '2.1'
services:
  db-mssql-express-2016:
    build:
     context: ..\
     dockerfile: \sql\Dockerfile
    environment:
      sa_password: "Password1"
      ACCEPT_EULA: Y

    ports:
      - "1433:1433"

  web-appleseed-portal:
    build:
      context: ..\
      dockerfile: portal\windows\Dockerfile
    
    depends_on:
      - "db-mssql-express-2016"

    links:
      - "db-mssql-express-2016"

    ports:
      - "80:80"
#Only use the below section if you want to live host on the external internet
#networks:
 # default:
  #  external:
   #   name: nat
