version: '1.0'
services:
  db:
    build:
     context: .
     #Testing direct file for now
     dockerfile: https://github.com/Appleseed/portal-stack/blob/master/docker/sql/Dockerfile
    environment:
      sa_password: "Password1"
    ports:
      - "1433:1433" # REMARK: This is currently required, needs investigation

  web:
    build:
      context: .
      # Testing direct file for now
      dockerfile: https://raw.githubusercontent.com/Appleseed/portal-stack/master/docker/portal/windows/Dockerfile
    environment:
     # - "Data:DefaultConnection:ConnectionString=Server=db,1433;Database=MusicStore;User Id=sa;Password=Password1;MultipleActiveResultSets=True"
    depends_on:
      - "db"
    ports:
      - "80:80"

networks:
  default:
    external:
      name: nat
